---
- name: Create uptime kuma container
  community.docker.docker_container:
    name: uptime_kuma
    image: louislam/uptime-kuma:1
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/uptime_kuma/data:/app/data"
    security_opts:
      - no-new-privileges:true
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.uptime.entrypoints: "http"
      traefik.http.routers.uptime.rule: "Host(`uptime.{{ domain }}`)"
      traefik.http.middlewares.uptime-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.uptime.middlewares: "uptime-https-redirect"
      traefik.http.routers.uptime-secure.entrypoints: "https"
      traefik.http.routers.uptime-secure.rule: "Host(`uptime.{{ domain }}`)"
      traefik.http.routers.uptime-secure.tls: "true"
      traefik.http.routers.uptime-secure.service: "uptime"
      traefik.http.routers.uptime-secure.middlewares: "authelia@docker"
      traefik.http.services.uptime.loadbalancer.server.port: "3001"
      traefik.docker.network: "homelab"
