---
- name: Create vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/vaultwarden/data:/data"
    networks:
      - name: homelab
