---
- name: Create wg container
  community.docker.docker_container:
    name: wireguard
    image: weejewel/wg-easy
    pull: true
    sysctls:
      "net.ipv4.ip_forward": "1"
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    state: started
    env:
      "PASSWORD": "{{ wg_password }}"
      "WG_HOST": "{{ ansible_default_ipv4.address }}"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - "{{ docker_dir }}/wg/:/etc/wireguard"
    restart_policy: unless-stopped
